//
// This file was generated by the JPA Modeler
//
package br.com.jonyfs.domain;

import java.io.Serializable;

/**
 * 
 */
public class LoginPK implements Serializable {

    private Long series;

    private Long user;

    public LoginPK() {
    }

    public LoginPK(Long series, Long user) {
        this.series = series;
        this.user = user;
    }

    public Long getSeries() {
        return this.series;
    }

    public void setSeries(Long series) {
        this.series = series;
    }

    public Long getUser() {
        return this.user;
    }

    public void setUser(Long user) {
        this.user = user;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (!java.util.Objects.equals(getClass(), obj.getClass())) {
            return false;
        }
        final LoginPK other = (LoginPK) obj;
        if (!java.util.Objects.equals(this.getSeries(), other.getSeries())) {
            return false;
        }
        if (!java.util.Objects.equals(this.getUser(), other.getUser())) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 97 * hash + (this.getSeries() != null ? this.getSeries().hashCode() : 0);
        hash = 97 * hash + (this.getUser() != null ? this.getUser().hashCode() : 0);
        return hash;
    }

    @Override
    public String toString() {
        return "LoginPK{" + " series=" + series + ", user=" + user + '}';
    }

}
