/**
 * This file was generated by the JPA Modeler
 */
package br.com.jonyfs.domain;

import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * 
 */
@Entity
public class User implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Column(unique = true, nullable = false, length = 100)
    @Basic
    @NotNull
    @Size(max = 50)
    private String username;

    @Column(nullable = false, length = 100)
    @Basic
    private String password;

    @Basic
    @NotNull
    private boolean enabled;

    @ManyToMany(targetEntity = Groups.class, mappedBy = "users")
    private List<Groups> groupses;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public boolean isEnabled() {
        return this.enabled;
    }

    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    public List<Groups> getGroupses() {
        return this.groupses;
    }

    public void setGroupses(List<Groups> groupses) {
        this.groupses = groupses;
    }

}
